//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Commands = new HashSet<Command>();
            this.Commands1 = new HashSet<Command>();
        }
    
        public int AddressID { get; set; }
        public string AddressCompany { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressZipCode { get; set; }
        public bool AddressType { get; set; }
        public bool AddressActive { get; set; }
        public int DeliverableCountryID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliverableCountry DeliverableCountry { get; set; }
        public virtual ICollection<Command> Commands { get; set; }
        public virtual ICollection<Command> Commands1 { get; set; }
    }
}
