//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public Adress()
        {
            this.Commands = new HashSet<Command>();
            this.Commands1 = new HashSet<Command>();
        }
    
        public int AdressID { get; set; }
        public string AdressCompany { get; set; }
        public string AdressLine1 { get; set; }
        public string AdressLine2 { get; set; }
        public string AdressZipCode { get; set; }
        public bool AdressType { get; set; }
        public bool AdressActive { get; set; }
        public int DeliverableCountryID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliverableCountry DeliverableCountry { get; set; }
        public virtual ICollection<Command> Commands { get; set; }
        public virtual ICollection<Command> Commands1 { get; set; }
    }
}
