//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public Command()
        {
            this.CommandLines = new HashSet<CommandLine>();
        }
    
        public int CommandID { get; set; }
        public System.DateTime CommandDate { get; set; }
        public System.DateTime CommandFicsalDate { get; set; }
        public string CommandeReference { get; set; }
        public int CommandStatusID { get; set; }
        public int DeliveryAddressID { get; set; }
        public Nullable<int> InvoiceAddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<CommandLine> CommandLines { get; set; }
        public virtual CommandStatu CommandStatu { get; set; }
    }
}
