//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandLine
    {
        public int CommandLineID { get; set; }
        public int CommandLineQuantity { get; set; }
        public decimal CommandLinePrice { get; set; }
        public int CommandID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Product Product { get; set; }
    }
}
