//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandStatu
    {
        public CommandStatu()
        {
            this.Commands = new HashSet<Command>();
        }
    
        public int CommandStatusID { get; set; }
        public string CommandStatusName { get; set; }
        public short CommandStatusProgress { get; set; }
        public int MediaID { get; set; }
    
        public virtual ICollection<Command> Commands { get; set; }
        public virtual Medium Medium { get; set; }
    }
}
