//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Adresses = new HashSet<Adress>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerCompany { get; set; }
        public bool CustomerActive { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<Adress> Adresses { get; set; }
        public virtual User User { get; set; }
    }
}
