//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverableCountry
    {
        public DeliverableCountry()
        {
            this.Adresses = new HashSet<Adress>();
            this.DeliverablePrices = new HashSet<DeliverablePrice>();
        }
    
        public int DeliverableCountryID { get; set; }
        public string DeliverableCountryName { get; set; }
    
        public virtual ICollection<Adress> Adresses { get; set; }
        public virtual ICollection<DeliverablePrice> DeliverablePrices { get; set; }
    }
}
