//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eShopDBEntities : DbContext
    {
        public eShopDBEntities()
            : base("name=eShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Command> Commands { get; set; }
        public DbSet<CommandLine> CommandLines { get; set; }
        public DbSet<CommandStatu> CommandStatus { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DeliverableCountry> DeliverableCountries { get; set; }
        public DbSet<DeliverablePrice> DeliverablePrices { get; set; }
        public DbSet<Medium> Media { get; set; }
        public DbSet<MediaType> MediaTypes { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductSizeCategory> ProductSizeCategories { get; set; }
        public DbSet<SizeCategory> SizeCategories { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
