//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CommandLines = new HashSet<CommandLine>();
            this.Prices = new HashSet<Price>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductLongDescription { get; set; }
        public string ProductReference { get; set; }
        public string ProductManufacturerReference { get; set; }
        public string ProductBarCode { get; set; }
        public System.DateTime ProductAddingDate { get; set; }
        public bool ProductDiscontinued { get; set; }
        public int VATCategoryID { get; set; }
        public int UnitTypeID { get; set; }
        public int CategoryID { get; set; }
        public int MediaID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CommandLine> CommandLines { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual VATCategory VATCategory { get; set; }
    }
}
