//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeCategory
    {
        public SizeCategory()
        {
            this.ProductSizeCategories = new HashSet<ProductSizeCategory>();
        }
    
        public int SizeCategoryID { get; set; }
        public string SizeCategoryName { get; set; }
        public string SizeCategoryInitial { get; set; }
    
        public virtual ICollection<ProductSizeCategory> ProductSizeCategories { get; set; }
    }
}
