//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitType
    {
        public UnitType()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int UnitTypeID { get; set; }
        public string UnitTypeName { get; set; }
        public string UnitTypeSymbol { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
