//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int UserID { get; set; }
        public string UserUsername { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public string UserSalt { get; set; }
        public System.DateTime UserRegisterDate { get; set; }
        public Nullable<System.DateTime> UserLastLoginDate { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
