//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATCategory
    {
        public VATCategory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int VATCategoryID { get; set; }
        public string VATCategoryName { get; set; }
        public decimal VATCategoryValue { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
